# File name: Boat.py
# Author: Sophia A
# Date created: April 1, 2025
# Description: This is a boat

import turtle

square = turtle.Turtle()
square.goto(-150, -100)
square.color("#70baec")
square.begin_fill()
square.forward(325)
square.left(90)
square.forward(200)
square.left(90)
square.forward(325)
square.left(90)
square.forward(200)
square.left(90)
square.end_fill()

square.goto(-150, -65)
square.color("#1f1ff6")
square.begin_fill()
square.forward(325)
square.right(90)
square.forward(35)
square.right(90)
square.forward(325)
square.right(90)
square.forward(35)
square.end_fill()

square.penup()
square.goto(-75, -35)
square.color("#7a3702")
square.begin_fill()
square.right(90)
square.pendown()
square.forward(150)
square.right(135)
square.forward(45)
square.right(45)
square.forward(85)
square.right(45)
square.forward(45)
square.right(45)
square.right(90)
square.forward(80)
square.end_fill()

square.color("#000000")
square.left(90)
square.forward(75)
square.penup()

square.color("#ffffff")
square.begin_fill()
square.left(135)
square.pendown()
square.forward(70)
square.left(135)
square.forward(100)
square.left(135)
square.forward(70)
square.end_fill()
square.penup()

square.color("#000000")
square.left(135)
square.pendown()
square.forward(75)
square.penup()

square.goto(-125, 65)
square.color("#ffff00")
square.begin_fill()
square.circle(20)
square.penup()
square.end_fill()
turtle.done()

# I finally finished - 4/4/25
